### ISSUE TITLE
Unsetting "object_ids" on all connections

### ISSUE THREAD

**Issue by seagyn** [kidunot89/wp-graphql-woocommerce#39]
**Describe the bug**
The filter added to `graphql_term_object_connection_query_args` is unsetting `$query['object_ids']` without checking the type that is being worked with. This means that if you want to limit connection terms to their object, you can't even if you set `shouldOnlyIncludeConnectedItems`.

**To Reproduce**
This query should only return 1 category on my side but it returns them all.
```
query getPosts {
    posts {
      edges {
        node {
          postId
          title
        	categories(where: {
            shouldOnlyIncludeConnectedItems: true
          }) {
            edges {
              node {
                name
              }
            }
          }
        }
      }
    }
  }
```

**Expected behavior**
The WooCommerce term connection should only unset "object_ids" on WooCommerce types and not effect other connections.

**Comment by kidunot89** [comment]
Fixed it in #30
