### ISSUE TITLE
Add name to ProductVariation

### ISSUE THREAD

**Issue by seagyn** [kidunot89/wp-graphql-woocommerce#41]
Really need `name` in ProductVariation type as this is useful for displaying specific names for specific variations example: "Hard Cover", "Soft Cover", "eBook"

**Comment by kidunot89** [comment]
Do you think you can make a list of fields you need? I'm still very much shaping the schema, and some input would go a long way.

**Comment by seagyn** [comment]
Sure:

- name String
- description String
- downloadable Boolean
- virtual Boolean
- purchasable / active / visible Boolean (should probably be 3 fields?)

That's it from the default screen.

**Comment by jake-101** [comment]
i agree
